apiVersion: v1
kind: Secret
metadata:
  name: video-secrets
  namespace: video-platform
type: Opaque
stringData:
  AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=<name>;AccountKey=<key>;EndpointSuffix=core.windows.net"
  AZURE_STORAGE_ACCOUNT_KEY: "<key>"   
